### PR TITLE
SGI overhaul 1

### PR DESCRIPTION
**Pull request by panzer1b**
Multiple changes in my attempts at balancing the gameplay while sticking as close to lore as i can.  Also made a few visual and audio edits cause the default SGI sound was not authentic to stargate.

Major highlights:

*shield rebalance so that AI isnt 100% screwed if they decide not to research shield tech early.  Its still very critical research, but at least now its theoretically possible to win without if you invest elsewhere (economy, weapons, ect).

*mega nerfed replicator's drone frenzy for capitals, same dmg but max 3 targets regardless of level.  Makes it authentic to lore (as its a extremely nasty and powerful attack), but nolonger decimates so many units per hit (3 aurora class battleships before could easily neutralize 50 ships alone because of that broken ability).

*replicator capitals decreased boosts when leveling, was OP when LV10 capitals could not be touched even by concentrated fire from 50 goauld frigates.  LV10 is still way better then LV1, but nolonger invulnerable to concentrated fire.

*minor edit to destiny cannon ability, it can now target any ship, and has better fx.  Also added custom sound file to it pulled from SGU episode where they blew up that drone carrier thingy.

*edited osiris to have better range and shifted its firepower to the frontal quarter.  Same total DPS, but its like 75% forwards now instead of a 1/3 split in firepower like b4.

*changed some titan stats, namely buffed the snakehead's sokar titan, same damage but i gave it ability to engage 5 targets per direction and extreme range, still sucks vs capitals/titans, but is actusally superior at fleet supression when dealing with lots of weaker ships (i didnt want to just plain boost dmg as itd be a carbon copy of the other titan, now its unique capability and actually useful if you bring alternative ways to take down titans).  Also massive boost to sokar shield, to the point it comes close to atlantis's shield numbers (its not quite "lore", but there was no other way to make it balanced without giving it stupidly high weapons and rendering the anubis pointless, will take a look in future at how this can be redone).

*nerfed replicator offensive titan's deployable turrets, they still do good dmg, but is nolonger the equivalent of 2 auroras in DPS against a single target.  These thinsg were absolutely broken b4, now they are actually useful but fair to fight against.

*nerfed replicator and meatbag offensive titans sheild number to make them more give/take compared to def titans.  they have insane damage potential (lagrangian gun is 1hit KO on replicators, meatbags have best DPS of any ship against single target), but are nolonger flat upgrades over defensive choices.

*redone primary railguns on meatbag titans to make them very very high dmg (2 shots most frigates), but fires very very slowly, same DPS, just more burst.  Also applies to teh railgun on human defensive cannon platform, slower ROF, jhigher burst DMG.

*changed starbases somewhat in weapons, more loreish damage numbers (beams hurt ALOT on both human and replicator guns), but same DPS, same as above, made many of these guns fire slower but hit much harder.

*nyx has more plasma dmg and way mess beam dmg, total DPS is same, just made it a bit more unique vs 304.

*304 beam dmg nerf, it really is too strong when you factor in its very useful nukeing ability (which is not autoenbaled for AI to use against you), and already has superior stats to nyx in the 1st place.

*reassigned some squadrons among meatbag ships, 304s, nyx, ect only carry 1 fighter/bomber slot to make them a bit give/take.  Carrier cerberus has 4 slots, so if you want loads of planes you need to sacrifice utility/firepower to bring it (cerberus is much worse then both nyx and 304 offensively).  A mixed fleet has negligible change, but it allows you to actually pick/choose tactics based of preference (cerberus b4 was pointless as it carried equal planes to the 304 with like 1.3 the offense).

*decreased number of starfighters per squadron to cut down lag issues, buffed HP/damage to keep their overall firepower similar to b4 so aside from lag (and less visible craft), no real change to gameplay here.

*overhauled muzzles on replicator ships, now they are consistent (all "pulse" guns have same fx), and imo better looking.  Also edited sound fx based on scenes from SGU so they sound authentic (at least relative to the destiny guns).  I wanted to have 2 different sets of sfx, one for destiny and a few older looking ships, 1 for new ones like auroras, but there were no good samples available in SGA to use so i stuck with 100% SGU sounds.  6 unique sound tracks, 2 for light weapons (the super fast firing anti-fighter ones), 2 for medium, and 2 unique to the destiny's heavy turret (one is for the turret firing, other for destiny's heavy turret ability).

*overhauled particles for human autocannons, projectiles muzzle flashes, and sfx.  Reassigned fx, blue is light anti-fighter, orange is medium caliber railgun (304's weapons in movies), and yellow is capital/titan weapons.  Added 2 sets of sounds as well, pulled from SG1 (orange railguns sourced from SG1-S09E22 ori massacre), and SGA (blue from SGU-S01E01 as i got a good track from that ground defense platform).  Overall it feels alot closer to the movies although its still a WIP, gonna see if i can increase density of weapons fire without increasing lag as the scenes in stargate were like way more dense with how much fire was there.  Also changed some of the missiles to be closer to lore, no more blue/red missile trails, all missile weapons use the conventional missle model.

*fixed meatbag defense cannon damage output.  Fires 100% of its damage in a single direction but is less effective against fighters and turns slower to compensate for this.  A group of these things can easily wipe out even a titan if you are not careful, but not quite as good as replicator beams are in raw DPS.

That and a few other changes i dont remember, but these are the major ones.  Its still not finished 100% (havent figured out how to balance the goualds properly without destroying lore of them being cannon fodder by the end of the series), but here is what i have sofar and hopefully this will help yall improve the mod.

### CODE REVIEW

**Comment by jeffg2k** [comment]
@panzer1b If you'd like to join the SGI team, we could use more eyes on balance and configuration.  You're already familiar with the Sins Mod format and appear very in tune with SGI, so if you'd like to work more closely with us, contact me [on our Discord channel](https://discordapp.com/channels/322849121956528139/322856260280254464) and we can discuss.  I think you'd be really excited to see what we have in work and integrating Wraith and Asgard. 

As for this pull request, any updates since your [last upload](https://github.com/StargateInvasion/SGI/issues/104)?  I'm fine with most of these changes and I've been trying to work through them when I have time.  Some of it looks like it was forked from an earlier version of SGI.  For example, Gameplay.constants is a older version and might not work with our latest code changes.  There are some errors to work out in dev mode as well.  I'm also not sure about the research changes.  We recently made changes to set the Heros as top priority, so they wouldn't hold up research for AI and would be one of the first things they try to unlock.  I wonder if you've tested that in recent releases and found it didn't work?  That solution would be preferred over delinking the research if it works as we desire.  We could do the same on other important race technologies such as shields.  I'm open to reducing those research things to create balance, but I think that would need broader agreement with the team.

**Comment by panzer1b** [comment]
I have extremely limited freetime myself (as much as i like my job the hours suck arss), but ill see what i can do.

Ill be glad to join you guys provided you are all ok with me being very off and on with my contributions (most of my time modding SGI is purely when i can find time and happen to be in the mood to mod something).  Ill be in touch, prolly earliest next weekend, need to prepare some stuff for the week now and cant spend any more time gaming till im done for the week :(

**Comment by jeffg2k** [comment]
@panzer1b what's your contact info?  Or you can hit us up in the discord channel.

**Comment by jeffg2k** [comment]
I'm going to close this pull request as I've replaced it with https://github.com/StargateInvasion/SGI/pull/108 which removes the conflicts and uses most of the changes.  I chose not to use the delinking of heros from ships for the Goa'uld as I believe this was resolved with setting the priority option.  I still think we need an automated way to spawn the heros, but the AI should be researching it.  We can revisit if this is not the case.

**Pull request closed without merging**
